name: Daily AI Briefing

on:
  schedule:
    # Runs Monday-Friday at 07:00 AM KST (22:00 UTC previous day)
    # Cron: minute hour day month weekday (0=Sun, 1=Mon, ..., 6=Sat)
    - cron: '0 22 * * 1-5'
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-briefing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      
      - name: Display Chrome version
        run: |
          chrome --version
      
      - name: Run daily briefing
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL_NAME: ${{ secrets.OPENAI_MODEL_NAME }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          TZ: Asia/Seoul
        run: |
          python run_daily_briefing.py
      
      - name: Upload logs (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs
          path: |
            *.log
            temp.pdf
          retention-days: 7

